# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20180917_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(related_name='_profile_followed_+', to='blogging.Profile'),
        ),
    ]
